FROM gradle:7.4-jdk11

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
    zip \
    unzip \
    curl \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm -rf /var/lib/apt/lists/*

RUN aws --version

CMD ["bash"]
